vanishingPts = [100, 10;
                150, 70;
                200, 10];
            
movingPts = [149, 30];

figure(1), hold on;
daspect([1 1 1]);
% Triangular formed by three vanishing points
plot(vanishingPts(:,1), vanishingPts(:,2), 'x', 'Color', 'Red', 'MarkerSize', 15, 'LineWidth', 2);
plot([vanishingPts(1,1), vanishingPts(2,1)], [vanishingPts(1,2), vanishingPts(2,2)], '-', 'Color', 'Green', 'LineWidth', 2);
plot([vanishingPts(1,1), vanishingPts(3,1)], [vanishingPts(1,2), vanishingPts(3,2)], '-', 'Color', 'Green', 'LineWidth', 2);
plot([vanishingPts(2,1), vanishingPts(3,1)], [vanishingPts(2,2), vanishingPts(3,2)], '-', 'Color', 'Green', 'LineWidth', 2);

% Moving points
plot(movingPts(:,1), movingPts(:,2), 'x', 'Color', 'Black', 'MarkerSize', 15, 'LineWidth', 2);
plot([movingPts(1), vanishingPts(1,1)], [movingPts(2), vanishingPts(1,2)], '-', 'Color', 'M', 'LineWidth', 1);
plot([movingPts(1), vanishingPts(2,1)], [movingPts(2), vanishingPts(2,2)], '-', 'Color', 'M', 'LineWidth', 1);
plot([movingPts(1), vanishingPts(3,1)], [movingPts(2), vanishingPts(3,2)], '-', 'Color', 'M', 'LineWidth', 1);

% p = alpha*p1 + beta*p2 + gamma*p3

tempVar =   -vanishingPts(2,1) * vanishingPts(3,2) + ...
            vanishingPts(2,1) * vanishingPts(1,2) + ...
            vanishingPts(1,1) * vanishingPts(3,2) + ... 
            vanishingPts(3,1) * vanishingPts(2,2) - ...            
            vanishingPts(3,1) * vanishingPts(1,2) - ...
            vanishingPts(1,1) * vanishingPts(2,2);
% beta = (x3*Y - x1*Y - x3*y1 - X*y3 + x1*y3 + X*y1 ) / (-x2*y3 + x2*y1 + x1*y3 + x3*y2 - x3*y1 - x1y2)       
beta =  (vanishingPts(3,1) * movingPts(2) - ...
        vanishingPts(1,1) * movingPts(2) - ...
        vanishingPts(3,1) * vanishingPts(1,2) - ...
        movingPts(1) * vanishingPts(3,2) + ...
        vanishingPts(1,1) * vanishingPts(3,2) + ...
        movingPts(1) * vanishingPts(1,2) ) / tempVar;
% gamma = (X*y2 - X*y1 - x1*y2 - x2*Y + x2*y1 + x1*Y) / (-x2*y3 + x2*y1 + x1*y3 + x3*y2 - x3*y1 - x1y2)
gamma =     (movingPts(1) * vanishingPts(2,2) - ...
            movingPts(1) * vanishingPts(1,2) - ...
            vanishingPts(1,1) * vanishingPts(2,2) - ...
            vanishingPts(2,1) * movingPts(2) + ...
            vanishingPts(2,1) * vanishingPts(1,2) + ...
            vanishingPts(1,1) * movingPts(2) ) / tempVar;
alpha = 1 - (beta + gamma);