function [ result ] = myFunc_xTheta(x,y,theta,phi,foc)
result = foc*x*sin(theta) + (cos(theta)*(foc*cos(phi) - foc*y*sin(phi)))...
        /(cos(theta)*(cos(phi) - y*sin(phi)) + x*sin(theta)) + (sin(theta)*...
        (foc*cos(phi) - foc*y*sin(phi))*(sin(theta)*(cos(phi) - y*sin(phi))...
        - x*cos(theta)))/(cos(theta)*(cos(phi) - y*sin(phi)) + x*sin(theta))^2;
end

